message: Hello I am from config server
kafka:
  order_placed_topic: order-placed-topic

server:
  port: 8085

logging:
  level:
    root: INFO
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orders
